name: Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ github.lawjohn19/lawrence-12-31-24 }}:latest .

      - name: Tag Docker image
        run: |
          docker tag ${{ github.lawjohn19/lawrence-12-31-24 }}:latest ${{ github.repository_lawjohn19 }}/docker-image:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ github.repository_lawjohn19 }}/docker-image:latest
